version: '3.3'
services:
  hamachi:
    image: gfjardim/hamachi
    container_name: hamachi
    network_mode: host
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '$HOME/.config/hamachi:/config'
    restart: always
    environment:
      - ACCOUNT="jack.hanley@redpillvr.com"
      - NETWORK="redpillvr-dev-docker"
      - PASS=""
    privileged: true
    
  mmo-server:
    build: ./mmo-server/.
    command: 'bash -c "cd /release/ && ./mmo-server -a  0.0.0.0:8080"'
    ports:
      - '8010:8080/udp'
      - '8080'
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=mmo.htpc
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    networks:
      app_net:
        ipv4_address: 192.168.88.20
            
  mmo-server1:
    build: ./mmo-server/.
    command: 'bash -c "cd /release/ && ./mmo-server -a  0.0.0.0:8080"'
    ports:
      - '8011:8080/udp'
      - '8080'
    environment:
      - VIRTUAL_PORT=8081
      - VIRTUAL_HOST=mmo.htpc
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    networks:
      app_net:
        ipv4_address: 192.168.88.21
            
  mmo-server2:
    build: ./mmo-server/.
    command: 'bash -c "cd /release/ && ./mmo-server -a  0.0.0.0:8080"'
    ports:
      - '8012:8080/udp'
      - '8080'
    environment:
      - VIRTUAL_PORT=8082
      - VIRTUAL_HOST=mmo.htpc
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    networks:
      app_net:
        ipv4_address: 192.168.88.22
            
  mmo-server3:
    build: ./mmo-server/.
    command: 'bash -c "cd /release/ && ./mmo-server -a  0.0.0.0:8080"'
    ports:
      - '8013:8080/udp'
      - '8080'
    environment:
      - VIRTUAL_PORT=8083
      - VIRTUAL_HOST=mmo.htpc
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    networks:
      app_net:
        ipv4_address: 192.168.88.23
            
  mmo-server4:
    build: ./mmo-server/.
    command: 'bash -c "cd /release/ && ./mmo-server -a  0.0.0.0:8080"'
    ports:
      - '8014:8080/udp'
      - '8080'
    environment:
      - VIRTUAL_PORT=8084
      - VIRTUAL_HOST=mmo.htpc
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    networks:
      app_net:
        ipv4_address: 192.168.88.24
  web:
    build: ./web/.
    image: 'nginx:stable-alpine'
    ports:
      - '80:80'
    environment:
      - VIRTUAL_PORT=81
      - VIRTUAL_HOST=mmo.htpc
      - NGINX_HOST=_
      - NGINX_PORT=80
      - MMO_SERVER_PORT=8010-8020
      - MMO_CLIENT_PORT=8081
      - MMO_MUMBLE_PORT=8082
      - MURMUR_PORT=64738
    command: |
      /bin/sh -c ' envsubst < /usr/share/nginx/www/index.html > /usr/share/nginx/html/index.html &&  envsubst < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf &&  nginx -g "daemon off;"'
    depends_on:
      - mmo-server
      - hamachi
    network_mode: host
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24
volumes:
  src: null