version: '2.1'
services:
    mmo-server:
        build: ./mmo-server/.
        command: bash -c "cd /release/ && ./mmo-server --address 0.0.0.0:8080"
        ports:
            - "8080:8080"
        volumes: 
            - ./mmo-server:/opt/mmo-server/src
        networks:
            app_net:
                ipv4_address: 172.16.238.10
    mmo-client:
        build: ./mmo-client/.
        command: bash -c "cd /release/ && ./mmo-client --address 0.0.0.0:8080"
        ports:
            - "8081:8080"
        volumes: 
            - ./mmo-client:/opt/mmo-client/src
        networks:
            app_net:
                ipv4_address: 172.16.238.11
    mmo-mumble:
        build: ./mmo-mumble/.
        command: bash -c "cd /release/ && ./mmo-mumble --address 0.0.0.0:8080 --cfg  /release/Config.toml"
        ports:
            - "8082:8080"
        volumes: 
            - ./mmo-mumble:/opt/mmo-mumble/src
        networks:
            app_net:
                ipv4_address: 172.16.238.12
    murmur:
        image: coppit/mumble-server:latest
        container_name: mumble-server
        command: /bin/bash -c "/tmp/start.sh"
        ports: 
            - 64738:64738
        volumes:
            - './murmur:/data'  
        networks:
            app_net:
                ipv4_address: 172.16.238.13
    web:
        image: nginx
        volumes:
            - "/c/Users/Public/sites:/usr/share/nginx/html"
            - "/c/Users/Public/sites/mysite.template:/etc/nginx/conf.d/mysite.template"
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        networks:
            app_net:
                ipv4_address: 172.16.238.14
networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1