version: '2.1'
services:
  mmo-server:
    build: ./mmo-server/.
    command: bash -c "cd /release/ && RUST_BACKTRACE=1 ./mmo-server --address  0.0.0.0:8080"
    ports:
      - '8080:8080/udp'
      - '8080:8080'
    volumes:
      - './mmo-server:/opt/mmo-server/src'
    networks:
      app_net:
        ipv4_address: 192.168.88.10
  mmo-client:
    build: ./mmo-client/.
    command: 'bash -c "cd /release/ && ./mmo-client --address 0.0.0.0:8080"'
    ports:
      - '8081:8080/udp'
      - '8081:8080'
    volumes:
      - './mmo-client:/opt/mmo-client/src'
    networks:
      app_net:
        ipv4_address: 192.168.88.11
  murmur:
    image: mattikus/murmur
    ports:
      - '64738:64738'
      - '64738:64738/udp'
    volumes:
      - './murmur:/data'
      - ./murmur/mumble-server.ini /etc/murmur.ini
    networks:
      app_net:
        ipv4_address: 192.168.88.12
  mmo-mumble:
    build: ./mmo-mumble/.
    ports:
      - '8082:8080/udp'
    volumes:
      - './mmo-mumble:/opt/mmo-mumble/src'
    networks:
      app_net:
        ipv4_address: 192.168.88.13
  web:
    image: 'nginx:stable-alpine'
    volumes:
      - './my/static/content:/usr/share/nginx/content'
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=_
      - NGINX_PORT=80
    networks:
      app_net:
        ipv4_address: 192.168.88.14
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24
          gateway: 192.168.88.1
