version: '2.1'
services:
    mmo-server:
        build: ./mmo-server/.
        command: bash -c "cd /release/ && ./mmo-server --address 0.0.0.0:8080"
        ports:
            - "8080:8080/udp"
            - "8080:8080"
        volumes: 
            - ./mmo-server:/opt/mmo-server/src
        networks:
            app_net:
                ipv4_address: 172.16.238.10
    mmo-client:
        build: ./mmo-client/.
        command: bash -c "cd /release/ && ./mmo-client --address 0.0.0.0:8080"
        ports:
            - "8081:8080/udp"
            - "8081:8080"
        volumes: 
            - ./mmo-client:/opt/mmo-client/src
        networks:
            app_net:
                ipv4_address: 172.16.238.11
    murmur:
        image: coppit/mumble-server@sha256:5325cb6556d7316a6be085fdc793366db16c04c1226b4c08ddce752a3754ee2b
        command: /bin/bash -c "/tmp/start.sh"
        ports: 
            - 64738:64738
            - 64738:64738/udp
        volumes:
            - './murmur/mumble-server.ini:/data/mumble-server.ini'  
        networks:
            app_net:
                ipv4_address: 172.16.238.12
    mmo-mumble:
        build: ./mmo-mumble/.
        #command: bash -c "/bin/bash"
        #command: bash -c "cd /release/ && ./mmo-mumble --address 172.16.238.12:64738 --config  /release/Config.toml --mumbleserver 172.16.238.12:64738"
        ports:
            - "8082:8080/udp"
        volumes: 
            - ./mmo-mumble:/opt/mmo-mumble/src
        networks:
            app_net:
                ipv4_address: 172.16.238.13
    web:
        image: nginx
        volumes:
            - ./my/static/content/:/usr/share/nginx/html/
            - ./my/static/content/web.template:/etc/nginx/conf.d/my_site.template
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=*
            - NGINX_PORT=80
        #command:  /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        # command: /bin/sh -c "envsubst < /usr/share/nginx/html/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        
        networks:
            app_net:
                ipv4_address: 172.16.238.14
networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1