version: '3.3'
services:
  mmo-server:
    build: ./mmo-server/.
    command: 'bash -c "cd /release/ &&./mmo-server -a  0.0.0.0:8080"'
    ports:
      - '8010:8080/udp'
      - '8080'
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    networks:
      app_net:
        ipv4_address: 192.168.88.20
  mmo-server.1:
    build: ./mmo-server/.
    command: 'bash -c "cd /release/ && ./mmo-server --address  0.0.0.0:8080"'
    ports:
      - '8011:8080/udp'
      - '8080'
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    networks:
      app_net:
        ipv4_address: 192.168.88.21
  mmo-server.2:
    build: ./mmo-server/.
    command: 'bash -c "cd /release/ && ./mmo-server --address  0.0.0.0:8080"'
    ports:
      - '8012:8080/udp'
      - '8080'
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    networks:
      app_net:
        ipv4_address: 192.168.88.22
  mmo-client:
    build: ./mmo-client/.
    command: 'bash -c "cd /release/ && ./mmo-client --address 0.0.0.0:8080"'
    ports:
      - '8081:8080/udp'
      - '8081:8080'
    networks:
      app_net:
        ipv4_address: 192.168.88.11
  murmur:
    image: mattikus/murmur
    ports:
      - '64738:64738'
      - '64738:64738/udp'
    volumes:
      - './murmur:/data'
      - ./murmur/mumble-server.ini /etc/murmur.ini
    networks:
      app_net:
        ipv4_address: 192.168.88.12
  mmo-mumble:
    build: ./mmo-mumble/.
    ports:
      - '8082:8080/udp'
    networks:
      app_net:
        ipv4_address: 192.168.88.13
  web:
    build: ./web/.
    image: 'nginx:stable-alpine'
    # volumes:
    #   - './web:/opt/web/src'
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=_
      - NGINX_PORT=80
      - MMO_SERVER_PORT=8010-8020
      - MMO_CLIENT_PORT=8081
      - MMO_MUMBLE_PORT=8082
      - MURMUR_PORT=64738
    command: |
      /bin/sh -c ' envsubst < /usr/share/nginx/www/index.html > /usr/share/nginx/html/index.html &&  envsubst < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf &&  nginx -g "daemon off;"'
    depends_on:
      - mmo-server
      - mmo-server.1
      - mmo-server.2
      - murmur
    networks:
      app_net:
        ipv4_address: 192.168.88.14
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24
volumes:
  src: null
