[package]
name = "mmo-client"
version = "0.1.0"
authors = ["Alex Rozgo <alex.rozgo@gmail.com>"]

[dependencies]
futures-preview = "0.3.0-alpha.3"
futures-cpupool = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
futures-await = "0.1"
clap = "2.24"